services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args: # ← このargsセクションを追加
        UID: "${UID}"
        GID: "${GID}"
    command: "./bin/rails server -b 0.0.0.0"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
    user: root