default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  user: postgres
  password: password

development:
  <<: *default
  database: diary_development

test:
  <<: *default
  database: diary_test